/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegistriesIndexRouteImport } from './routes/registries.index'
import { Route as RegistriesRegistryIdRouteImport } from './routes/registries.$registryId'
import { Route as RegistriesNewRouteImport } from './routes/registries.new'
import { Route as CRegistryIdNameRouteImport } from './routes/c.$registryId.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesIndexRoute = RegistriesIndexRouteImport.update({
  id: '/registries/',
  path: '/registries/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesRegistryIdRoute = RegistriesRegistryIdRouteImport.update({
  id: '/registries/$registryId',
  path: '/registries/$registryId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesNewRoute = RegistriesNewRouteImport.update({
  id: '/registries/new',
  path: '/registries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CRegistryIdNameRoute = CRegistryIdNameRouteImport.update({
  id: '/c/$registryId/$name',
  path: '/c/$registryId/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/registries/$registryId': typeof RegistriesRegistryIdRoute
  '/registries/new': typeof RegistriesNewRoute
  '/registries/': typeof RegistriesIndexRoute
  '/c/$registryId/$name': typeof CRegistryIdNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/registries/$registryId': typeof RegistriesRegistryIdRoute
  '/registries/new': typeof RegistriesNewRoute
  '/registries': typeof RegistriesIndexRoute
  '/c/$registryId/$name': typeof CRegistryIdNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/registries/$registryId': typeof RegistriesRegistryIdRoute
  '/registries/new': typeof RegistriesNewRoute
  '/registries/': typeof RegistriesIndexRoute
  '/c/$registryId/$name': typeof CRegistryIdNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/registries/$registryId'
    | '/registries/new'
    | '/registries/'
    | '/c/$registryId/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/registries/$registryId'
    | '/registries/new'
    | '/registries'
    | '/c/$registryId/$name'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/registries/$registryId'
    | '/registries/new'
    | '/registries/'
    | '/c/$registryId/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  RegistriesRegistryIdRoute: typeof RegistriesRegistryIdRoute
  RegistriesNewRoute: typeof RegistriesNewRoute
  RegistriesIndexRoute: typeof RegistriesIndexRoute
  CRegistryIdNameRoute: typeof CRegistryIdNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries/': {
      id: '/registries/'
      path: '/registries'
      fullPath: '/registries/'
      preLoaderRoute: typeof RegistriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries/$registryId': {
      id: '/registries/$registryId'
      path: '/registries/$registryId'
      fullPath: '/registries/$registryId'
      preLoaderRoute: typeof RegistriesRegistryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries/new': {
      id: '/registries/new'
      path: '/registries/new'
      fullPath: '/registries/new'
      preLoaderRoute: typeof RegistriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$registryId/$name': {
      id: '/c/$registryId/$name'
      path: '/c/$registryId/$name'
      fullPath: '/c/$registryId/$name'
      preLoaderRoute: typeof CRegistryIdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  RegistriesRegistryIdRoute: RegistriesRegistryIdRoute,
  RegistriesNewRoute: RegistriesNewRoute,
  RegistriesIndexRoute: RegistriesIndexRoute,
  CRegistryIdNameRoute: CRegistryIdNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
