import { Link, createFileRoute } from "@tanstack/react-router"
import { Bot, ExternalLink, FileCode2, TriangleAlert } from "lucide-react"
import { CodeBlock } from "~/components/code-block"
import { ComponentCard, Screenshot } from "~/components/component-card"
import { CopyButton } from "~/components/copy-button"
import { Badge } from "~/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs"
import { getComponentFn } from "~/server/components"
import { toAgentMarkdown } from "~/server/dto"

export const Route = createFileRoute("/c/$registryId/$name")({
  loader: ({ params }) => getComponentFn({ data: params }),
  head: ({ loaderData }) => ({
    meta: loaderData
      ? [{ title: `${loaderData.title} · ${loaderData.registryId} — Shadcn Explorer` }, { name: "description", content: loaderData.doc?.summary ?? loaderData.description }]
      : [],
  }),
  component: ComponentPage,
})

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="scroll-mt-20 flex flex-col gap-3">
      <h2 className="border-b pb-2 text-xl font-semibold tracking-tight">{title}</h2>
      {children}
    </section>
  )
}

function ComponentPage() {
  const d = Route.useLoaderData()
  const pm = [
    { label: "npx", cmd: d.installCommand },
    { label: "pnpm", cmd: d.installCommand.replace(/^npx /, "pnpm dlx ") },
    { label: "bun", cmd: d.installCommand.replace(/^npx /, "bunx --bun ") },
  ]
  const toc = [
    ["installation", "Installation"],
    ...(d.doc ? [["usage", "Usage"], ["examples", "Examples"]] : []),
    ...(d.doc?.props.length ? [["props", "API Reference"]] : []),
    ["agent", "Use with Coding Agent"],
    ["files", "Files & Dependencies"],
  ] as const

  return (
    <div className="grid gap-10 pt-10 xl:grid-cols-[1fr_220px]">
      <article className="flex min-w-0 flex-col gap-10">
        <header className="flex flex-col gap-3">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Link to="/registries/$registryId" params={{ registryId: d.registryId }} className="hover:text-foreground">
              {d.registry.namespace ?? d.registry.name}
            </Link>
            <span>/</span>
            <span className="font-mono">{d.name}</span>
          </div>
          <h1 className="text-3xl font-bold tracking-tight">{d.title}</h1>
          <p className="text-lg text-muted-foreground">{d.doc?.summary ?? d.description}</p>
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline" className="font-mono">
              {d.kind}
            </Badge>
            {d.categories.map((c) => (
              <Badge key={c} variant="secondary">
                {c}
              </Badge>
            ))}
            <a href={d.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground">
              registry-item.json <ExternalLink className="size-3" />
            </a>
          </div>
          {d.status.doc !== "Generated" && (
            <div className="flex items-start gap-2 rounded-lg border border-dashed p-3 text-sm text-muted-foreground">
              <TriangleAlert className="mt-0.5 size-4 shrink-0" />
              {d.docError
                ? `Usage docs could not be generated: ${d.docError}`
                : "Usage docs and preview are being generated by the coding agent. Registry metadata is shown meanwhile."}
            </div>
          )}
        </header>

        <Tabs defaultValue="preview">
          <TabsList>
            <TabsTrigger value="preview">Preview</TabsTrigger>
            {d.previewHtmlUrl && <TabsTrigger value="live">Live</TabsTrigger>}
            {d.doc && <TabsTrigger value="code">Code</TabsTrigger>}
          </TabsList>
          <TabsContent value="preview">
            <Screenshot card={d} className="flex min-h-[360px] items-center justify-center rounded-xl border bg-muted/20 p-6" />
          </TabsContent>
          {d.previewHtmlUrl && (
            <TabsContent value="live">
              {/* Agent 生成の HTML は allow-same-origin を付けず不透明オリジンで実行する */}
              <iframe title={`${d.title} live preview`} src={d.previewHtmlUrl} sandbox="allow-scripts" className="h-[480px] w-full rounded-xl border bg-background" />
            </TabsContent>
          )}
          {d.doc && (
            <TabsContent value="code">
              <CodeBlock code={d.doc.examples[0]?.code ?? d.doc.usage} title="demo.tsx" />
            </TabsContent>
          )}
        </Tabs>

        <Section id="installation" title="Installation">
          <Tabs defaultValue="npx">
            <TabsList>
              {pm.map((p) => (
                <TabsTrigger key={p.label} value={p.label}>
                  {p.label}
                </TabsTrigger>
              ))}
            </TabsList>
            {pm.map((p) => (
              <TabsContent key={p.label} value={p.label}>
                <CodeBlock code={p.cmd} title="terminal" />
              </TabsContent>
            ))}
          </Tabs>
          {d.registry.namespace && (
            <p className="text-sm text-muted-foreground">
              Requires <code className="font-mono">{d.registry.namespace}</code> in the <code className="font-mono">registries</code> of your
              components.json (shadcn adds official directory namespaces automatically).
            </p>
          )}
        </Section>

        {d.doc && (
          <>
            <Section id="usage" title="Usage">
              <CodeBlock code={d.doc.usage} title="usage.tsx" />
              {d.doc.whenToUse.length > 0 && (
                <ul className="list-disc space-y-1 pl-5 text-sm text-muted-foreground">
                  {d.doc.whenToUse.map((w) => (
                    <li key={w}>{w}</li>
                  ))}
                </ul>
              )}
            </Section>
            <Section id="examples" title="Examples">
              {d.doc.examples.map((ex) => (
                <div key={ex.title} className="flex flex-col gap-2">
                  <h3 className="font-medium">{ex.title}</h3>
                  <p className="text-sm text-muted-foreground">{ex.description}</p>
                  <CodeBlock code={ex.code} title={`${ex.title.toLowerCase().replace(/\s+/g, "-")}.tsx`} />
                </div>
              ))}
            </Section>
            {d.doc.props.length > 0 && (
              <Section id="props" title="API Reference">
                <div className="overflow-x-auto rounded-lg border">
                  <table className="w-full text-sm">
                    <thead className="bg-muted/50 text-left">
                      <tr>
                        <th className="px-3 py-2 font-medium">Prop</th>
                        <th className="px-3 py-2 font-medium">Type</th>
                        <th className="px-3 py-2 font-medium">Default</th>
                        <th className="px-3 py-2 font-medium">Description</th>
                      </tr>
                    </thead>
                    <tbody>
                      {d.doc.props.map((p) => (
                        <tr key={p.name} className="border-t">
                          <td className="px-3 py-2 font-mono">{p.name}</td>
                          <td className="px-3 py-2 font-mono text-xs">{p.type}</td>
                          <td className="px-3 py-2 font-mono text-xs">{p.default ?? "—"}</td>
                          <td className="px-3 py-2 text-muted-foreground">{p.description}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </Section>
            )}
            {d.doc.accessibility.length > 0 && (
              <Section id="a11y" title="Accessibility">
                <ul className="list-disc space-y-1 pl-5 text-sm text-muted-foreground">
                  {d.doc.accessibility.map((a) => (
                    <li key={a}>{a}</li>
                  ))}
                </ul>
              </Section>
            )}
          </>
        )}

        <Section id="agent" title="Use with Coding Agent">
          <p className="text-sm text-muted-foreground">
            Paste this into Claude Code, Codex or Cursor. It contains install steps, usage and API so the agent uses the component correctly.
          </p>
          <div className="flex flex-wrap gap-2">
            <CopyButton value={toAgentMarkdown(d)} label="Copy docs as Markdown" />
            {d.doc?.agentPrompt && <CopyButton value={d.doc.agentPrompt} label="Copy agent prompt" />}
          </div>
          {d.doc?.agentPrompt && <CodeBlock code={d.doc.agentPrompt} title="prompt" />}
          <div className="flex items-start gap-2 rounded-lg border bg-muted/30 p-3 text-sm">
            <Bot className="mt-0.5 size-4 shrink-0 text-brand" />
            <span>
              Or let your agent search by itself via MCP — see{" "}
              <Link to="/settings" className="underline">
                API & MCP
              </Link>
              .
            </span>
          </div>
        </Section>

        <Section id="files" title="Files & Dependencies">
          <ul className="flex flex-col gap-1 text-sm">
            {d.files.map((f) => (
              <li key={f.path} className="flex items-center gap-2 font-mono text-xs">
                <FileCode2 className="size-3.5 text-muted-foreground" />
                {f.path}
                {f.target && <span className="text-muted-foreground">→ {f.target}</span>}
              </li>
            ))}
          </ul>
          {d.dependencies.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
              {d.dependencies.map((dep) => (
                <Badge key={dep} variant="outline" className="font-mono">
                  {dep}
                </Badge>
              ))}
            </div>
          )}
          {d.related.length > 0 && (
            <div className="grid grid-cols-1 gap-3 pt-2 sm:grid-cols-3">
              {d.related.map((r) => (
                <ComponentCard key={r.id} card={r} />
              ))}
            </div>
          )}
        </Section>
      </article>

      <aside className="hidden xl:block">
        <nav className="sticky top-20 flex flex-col gap-2 text-sm">
          <p className="font-medium">On this page</p>
          {toc.map(([id, label]) => (
            <a key={id} href={`#${id}`} className="text-muted-foreground hover:text-foreground">
              {label}
            </a>
          ))}
        </nav>
      </aside>
    </div>
  )
}
